apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dummy-admin
  namespace: dummy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: namespace-admin
subjects:
- kind: ServiceAccount
  name: dummy
  namespace: dummy
