apiVersion: app.helloworld.io/v1alpha1
kind: Operator
metadata:
  name: helloworld
  namespace: prod-common
spec:
  size: 1
  response: "Hello, World - REST API!"
  image: "ghcr.io/berndonline/k8s/go-helloworld:latest"
  mongodb: false
  jaegercollector:
    - "--reporter.grpc.host-port=dns:///jaeger-collector-headless.observability:14250"
    - "--reporter.type=grpc"
