apiVersion: addons.cluster.x-k8s.io/v1alpha3
kind: ClusterResourceSet
metadata:
  name: non-prod-eu-west-1-cni
  namespace: non-prod-eu-west-1
spec:
  clusterSelector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: non-prod-eu-west-1
  resources:
  - kind: ConfigMap
    name: calico-cni
