apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tenants-non-prod
  namespace: non-prod-eu-west-1
spec:
  interval: 5m
  path: ./tenants/aws/non-prod
  prune: true
  sourceRef:
    kind: GitRepository
    name: main
    namespace: flux-system
  kubeConfig:
    secretRef:
      name: non-prod-eu-west-1-kubeconfig
