apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: feature-access-control
  namespace: non-prod-eu-west-1
spec:
  interval: 5m
  path: ./features/access-control
  prune: true
  sourceRef:
    kind: GitRepository
    name: main
    namespace: flux-system
  kubeConfig:
    secretRef:
      name: non-prod-eu-west-1-kubeconfig
