apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
  name: k8s-helloworld-operator-controller-manager-metrics-service
  namespace: helloworld-operator
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: controller-manager
