apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: mgmt
  namespace: flux-system
spec:
  decryption:
    provider: sops
  interval: 5m0s
  path: ./providers/aws/v1/mgmt
  prune: true
  sourceRef:
    kind: GitRepository
    name: main
