apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: feature-access-control
  namespace: flux-system
spec:
  decryption:
    provider: sops
  interval: 5m0s
  path: ./features/access-control
  prune: true
  sourceRef:
    kind: GitRepository
    name: release
