apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: AWSCluster
metadata:
  name: prod-eu-west-1
  namespace: prod-eu-west-1
spec:
  region: eu-west-1
  sshKeyName: default
  # networkSpec:
  #   vpc:
  #     id: vpc-0425c335226437144
  #   subnets:
  #   - id: subnet-0261219d564bb0dc5
  #   - id: subnet-0fdcccba78668e013
  networkSpec:
    vpc:
      cidrBlock: "10.0.0.0/23"
    subnets:
    - availabilityZone: eu-west-1a
      cidrBlock: "10.0.0.0/27"
      isPublic: true
    # - availabilityZone: eu-west-1b
    #   cidrBlock: "10.0.0.32/27"
    #   isPublic: true
    # - availabilityZone: eu-west-1c
    #   cidrBlock: "10.0.0.64/27"
    #   isPublic: true
    - availabilityZone: eu-west-1a
      cidrBlock: "10.0.1.0/27"
    # - availabilityZone: eu-west-1b
    #   cidrBlock: "10.0.1.32/27"
    # - availabilityZone: eu-west-1c
    #   cidrBlock: "10.0.1.64/27"
