apiVersion: cluster.x-k8s.io/v1alpha3
kind: Cluster
metadata:
  name: prod-eu-west-1
  namespace: prod-eu-west-1
  labels:
    cluster.x-k8s.io/cluster-name: prod-eu-west-1
spec:
  clusterNetwork:
    services:
      cidrBlocks:
      - 172.30.0.0/16
    pods:
      cidrBlocks:
      - 10.128.0.0/14
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    kind: KubeadmControlPlane
    name: prod-eu-west-1-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: AWSCluster
    name: prod-eu-west-1
