apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: feature-helloworld-operator
  namespace: prod-eu-west-1
spec:
  interval: 5m
  path: ./features/helloworld-operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: release
    namespace: flux-system
  kubeConfig:
    secretRef:
      name: prod-eu-west-1-kubeconfig
