apiVersion: cluster.x-k8s.io/v1alpha3
kind: MachineDeployment
metadata:
  name: prod-eu-west-1-data-plane
  namespace: prod-eu-west-1
spec:
  clusterName: prod-eu-west-1
  replicas: 3
  selector:
    matchLabels: null
  template:
    metadata:
      labels:
        "nodepool": "nodepool-0"
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
          kind: KubeadmConfigTemplate
          name: prod-eu-west-1-data-plane
      clusterName: prod-eu-west-1
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
        kind: AWSMachineTemplate
        name: prod-eu-west-1-data-plane
      version: v1.24.0
