apiVersion: v1
kind: LimitRange
metadata:
  name: default
  namespace: dummy
spec:
  limits:
  - default:
      cpu: 100m
      memory: 100Mi
    defaultRequest:
      cpu: 50m
      memory: 50Mi
    type: Container
